version: '3.8'

services:
  learning-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5247:80"
    environment:
      - JWT_SECRET=my-32-character-ultra-secure-and-ultra-long-secret
      - CONNECTION_STRING=Host=db;Port=3307;Database=${MYSQL_DATABASE};User=${MYSQL_USER};Password=${MYSQL_PASSWORD}Charset=utf8mb4;;
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3

volumes:
  db_data:
